### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Abdul-Ahad-Supto** [zemetsskiy/ZealyAutomatization#12]
Traceback (most recent call last):
  File "c:\Users\User\Pictures\ZealyAutomatization-master\main.py", line 3, in <module>
    from ZealyClient import ZealyClient
  File "c:\Users\User\Pictures\ZealyAutomatization-master\ZealyClient.py", line 4, in <module>
    from config.quests import quests
ModuleNotFoundError: No module named 'config.quests'

**Comment by sorcer1122** [comment]
install config.quests module for pip
